#!/bin/sh
#           _                 _       __       
#  _ __ ___| | ___   __ _  __| | ___ / _| __ _ 
# | '__/ _ \ |/ _ \ / _` |/ _` |/ __| |_ / _` |
# | | |  __/ | (_) | (_| | (_| | (__|  _| (_| |
# |_|  \___|_|\___/ \__,_|\__,_|\___|_|  \__, |
#                                        |___/ 
#
# A script to reload all the different part of the configuration
# Author: Aurélien Blicq

killall -SIGUSR1 tint2
